# Generated by Django 2.2.5 on 2019-11-06 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposals',
            name='sec_id',
        ),
        migrations.AddField(
            model_name='secretaries',
            name='year',
            field=models.IntegerField(default=2019),
            preserve_default=False,
        ),
    ]
