# Generated by Django 2.2.5 on 2019-11-06 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_auto_20191106_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposals',
            name='date',
            field=models.DateTimeField(default='2019-11-06 20:37:04.662992'),
        ),
    ]
