# Generated by Django 2.2.5 on 2019-11-06 21:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_proposals_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='society',
            name='soc_name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proposals',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
